CREATE TABLE beers (
    id SERIAL PRIMARY KEY,
    foreign_id INTEGER UNIQUE NOT NULL,
    name VARCHAR(128) NOT NULL,
    tagline VARCHAR(128),
    description TEXT,
    image_url VARCHAR(512),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_beers (
    id SERIAL PRIMARY KEY,
    beer_id INTEGER NOT NULL REFERENCES beers(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)
