CREATE TABLE favorites (
    id INTEGER PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    tagline VARCHAR(128),
    description TEXT,
    beer_image VARCHAR(512),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_favorites (
    id SERIAL PRIMARY KEY,
    favorite_id INTEGER NOT NULL REFERENCES favorites(id),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)
